name: 'Run EE Server'
description: 'Run EE server. Returns once server is ready. Only tested on Linux and macOS'
# NOTE: do not share this server container with others
# since it's using the default admin / admin credentials
inputs:
  # All inputs in composite actions are strings
  server-tag:
    description: Server version to use
    required: false
    default: "latest"
  container-repo-url:
    required: false
    description: Container repo url
    default: aerospike.jfrog.io/
  jfrog-platform-url:
    description: "JFrog platform url"
    required: false
    default: https://aerospike.jfrog.io
  oidc-provider:
    description: "OIDC provider name"
    required: true
  oidc-audience:
    description: "OIDC audience"
    required: true
  container-name:
    default: aerospike
    required: false
    description: Name for test container
  server-type:
    required: true
    default: aerospike-server-enterprise
    description: Server type `aerospike-server` or `aerospike-server-enterprise`

runs:
  using: "composite"
  steps:
  - name: Set up JFrog credentials
    id: setup-jfrog-cli
    uses: jfrog/setup-jfrog-cli@v4
    env:
      JF_URL: ${{ inputs.jfrog-platform-url }}
      JF_PROJECT: database
    with:
      oidc-provider-name: ${{ inputs.oidc-provider }}
      oidc-audience: ${{ inputs.oidc-audience }}

  - run: docker login ${{ inputs.container-repo-url }} --username ${{ steps.setup-jfrog-cli.outputs.oidc-user }} --password ${{ steps.setup-jfrog-cli.outputs.oidc-token }}
    shell: bash

  - run: echo IMAGE_NAME=aerospike.jfrog.io/oci/${{ inputs.server-type }}:${{ inputs.server-tag }} >> $GITHUB_ENV
    shell: bash

  - run: docker run -d --name ${{ inputs.container-name }} -p 3000:3000 ${{ env.IMAGE_NAME }}
    shell: bash

  - uses: ./.github/actions/wait-for-as-server-to-start
    with:
      container-name: ${{ inputs.container-name }}
      is-security-enabled: false
      is-strong-consistency-enabled: true

  # All the partitions are assumed to be dead when reusing a roster file
  - run: docker exec ${{ inputs.container-name }} asadm --enable --execute "manage revive ns test"
    shell: bash

  # Apply changes
  - run: docker exec ${{ inputs.container-name }} asadm --enable --execute "manage recluster"
    shell: bash

  # For debugging
  - run: docker logs aerospike
    shell: bash
