version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
    target-branch: stage
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
