version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
    target-branch: stage
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: "/"
    target-branch: stage
    schedule:
      interval: weekly
    groups:
      dependencies:
          patterns:
            - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /AerospikeAdmin
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /AerospikeBenchmarks
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /AerospikeClient
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /AerospikeExample
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /AerospikeTest
    schedule:
      interval: weekly
