logging {
    console {
        context any debug
    }
}

namespace test {
    default-ttl 2592000
    nsup-period 120
    replication-factor 1
    strong-consistency true
    strong-consistency-allow-expunge true
    storage-engine device {
        file /opt/aerospike/data/test.dat
        filesize 4294967296
        read-page-cache true
    }
}

network {
    fabric {
        address local
        port 3001
    }
    heartbeat {
        address local
        interval 150
        mode mesh
        port 3002
        timeout 10
    }
    service {
        address any
        port 3000
    }
}

service {
    cluster-name docker
    feature-key-file /etc/aerospike/features.conf
}
