name: PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate:
    uses: aerospike/shared-workflows/.github/workflows/reusable_pr-hygiene.yml@07c958ca4c5cea494dc8790949c08e3fb28c55e1 # v3.3.0
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr-labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}
      allowed-patterns: |
        ^[a-zA-Z]+\(deps[^)]*\):
        ^\[StepSecurity\]
        ^[Rr]evert "
        ^revert:
        ^Bump version to
        ^Bump
